### ISSUE TITLE
Upgrade to show how to test redux-form v6.

### ISSUE THREAD

**Issue by jckdrpr** [tylercollier/redux-form-test#5] opened 2016-09-05 11:00 UTC
Hi nice examples but I was wondering are you planning to add examples on how to test redux-form v6. as I was trying to do it but I am pretty much clueless on how to do this?

**Comment by tylercollier** [comment] 2016-09-07 05:34
Thanks for the reminder on this. I haven't used v6 yet myself. I've marked it on my calendar to take a stab at this this weekend.

**Comment by tylercollier** [comment] 2016-09-12 09:59
I got a good start on this. I've done the unit tests. You can see on the [redux-form-v6](https://github.com/tylercollier/redux-form-test/tree/redux-form-v6) branch. You can [compare it to master](https://github.com/tylercollier/redux-form-test/compare/redux-form-v6?diff=split&name=redux-form-v6) to see the changes, however be advised that I changed the extension of the ContactFormComponent from .jsx to .js, which makes the commit look longer than it should because it doesn't simply show that the file was renamed; it makes it look like the .jsx file was deleted and a .js file was added, which also makes comparing the changes harder.

The remaining piece is the integration tests. I made the tests more realistic by having a real `onSave` function that gets passed into the `ContactFormContainer` using `mapDispatchToProps`, and the problem is that it overrides the `onSave` stub from the test. This exposes a weakness to the integration tests as they existed previously. I think I know how to solve this and will get to it on Monday or the following weekend.

**Comment by tylercollier** [comment] 2016-09-26 06:49
I've fixed the integration test, and merged this with master. Please take a look at the updated readme. I've updated much of the code and comments inside.

I'm closing this issue, but feel free to ask any additional questions, like if you had a specific example or difficult scenario.

**Closed by tylercollier** 2016-09-26 06:49 UTC

**Comment by jckdrpr** [comment] 2016-09-26 10:30
Thank you, this repo has been a great help but for what I required it got postponed :( so it will be a while when I check it out again.
